#!/bin/sh

set -eu

npm run build

if [ -n "$(git status --porcelain lib dist)" ]; then
    git add -- lib dist
    git commit --only --no-verify -m "generate lib and dist files" -- lib dist

    echo "Generated and committed lib and dist files. Run git push again to push the new commit."
    exit 1
fi
